name: Build Bettercap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build Bettercap
        run: go build -tags "nousb" -o bettercap.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bettercap-windows
          path: bettercap.exe
