name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'

      - name: Build Bettercap (Windows)
        run: |
          go mod tidy
          go build -tags "nousb" -o bettercap.exe ./cmd/bettercap

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bettercap-windows
          path: bettercap.exe
