name: Go Build and Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libpcap-dev \
            libusb-1.0-0-dev \
            pkg-config

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build project
        run: |
          go mod tidy
          go build -o myapp.exe .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-artifact
          path: myapp.exe
